# Generated by Django 2.2.16 on 2023-01-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20221228_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Напишите ваши мысли, по поводу поста (будьте вежливы)', verbose_name='Комментарий'),
        ),
    ]
